# -*- coding: utf-8 -*-
"""Caesar Cipher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i2IsTB3lQIev14ehFObSsVVddtw8LTOM
"""

def encrypt(text, shift):
    result = ""
    for char in text:
        if char.isalpha():
            base = 'A' if char.isupper() else 'a'
            result += chr((ord(char) - ord(base) + shift) % 26 + ord(base))
        else:
            result += char
    return result

def decrypt(text, shift):
    return encrypt(text, -shift)

# Main program
def caesar_cipher():
    action = input("Type 'E' to encrypt or 'D' to decrypt: ").lower()

    if action not in ['e', 'd']:
        print("Invalid option! Choose 'E' or 'D'.")
        return

    message = input("Enter the message: ")
    shift = int(input("Enter the shift number: "))

    if action == 'e':
        print("Encrypted message:", encrypt(message, shift))
    else:
        print("Decrypted message:", decrypt(message, shift))

caesar_cipher()